name: Ping Scheduler

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test scheduler
        run: echo "Scheduler works!"
